"""empty message

Revision ID: 113a1f19592f
Revises: 
Create Date: 2018-06-19 17:01:29.546631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '113a1f19592f'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('test_table')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rawData', postgresql.JSONB(), autoincrement=False, nullable=True),
    sa.Column('merchantAccountCode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pspReference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('merchantReference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eventDate', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('eventCode', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('paymentMethod', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('originalReference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    # ### end Alembic commands ###
